package page_Xpaths;

import org.openqa.selenium.By;

public class Elements {
	
	public By pt = By.xpath("//span[@class='iconTextLinks__text visible-in-Desktop']");
	public By colours2200=By.linkText("2200 Colours");
	public By colours2200list=By.xpath("//span[@class='color-catalogue-revamp-list--colorTitle']");
	public By understand=By.xpath("//button[text()='I understand']");
	public By colourcombination1=By.xpath("(//li[@class='colorCodeWrap']/a)[2]");
	public By warm=By.xpath("(//span[@class='spriteIcon-Aprevamp customCheckBox-unchecked'])[2]");
	public By light=By.xpath("(//span[@class='spriteIcon-Aprevamp customCheckBox-unchecked'])[3]");
	public By Bedroom=By.xpath("(//span[@class='spriteIcon-Aprevamp customCheckBox-unchecked'])[6]");
	public By Interior_Textures=By.linkText("Interior Textures");
	public By colourcombination2=By.xpath("(//li[@class='colorCodeWrap']/a)[4]");
	public By filterby=By.xpath("//button[@class='btn filter-btn']");
	public By filter1=By.xpath("(//span[@class='for-desktop track_filter_btn'])[1]");
	public By filter2=By.xpath("(//span[@class='for-desktop track_filter_btn'])[7]");
	public By filter3=By.xpath("(//span[@class='for-desktop track_filter_btn'])[9]");
	public By applybutton=By.xpath("//button[@class='btn plp-btn filled']");
	public By result_list=By.xpath("//h3[@class='color-name m-0']");
	public By Exterior_Textures=By.linkText("Exterior Textures");
	public By paint_bud_calc=By.linkText("Paint Budget Calculator");
	public By repaint=By.xpath("(//span[@class='form-global__custom-element form-radio-input__custom-element align-middle'])[2]");
	public By exte=By.xpath("(//span[@class='form-global__custom-element form-radio-input__custom-element align-middle'])[4]");
	public By sizeofhome=By.xpath("(//span[@class='form-global__custom-element form-radio-input__custom-element align-middle'])[6]");
	public By sqfeet=By.xpath("//input[@class='form-global__field form-text-input__field']");
	public By calculatenow=By.xpath("//div[@class='ctaComp calculate-now track_calculate']");
	public By budget_product=By.xpath("(//div[@class='slick-list draggable'])[3]/div/div/div/div");
	public By paintselect=By.linkText("Paint Selector");
	public By filter4=By.xpath("(//span[@class='for-desktop track_filter_btn'])[12]");
	public By filter5=By.xpath("(//span[@class='for-desktop track_filter_btn'])[32]");
	public By filter6=By.xpath("(//span[@class='for-desktop track_filter_btn'])[61]");
	public By paintsresult=By.xpath("//div[@class='similarProdItem rhs-listing-variants d-flex-custom']/div");
	public By paintname=By.xpath("//div[@class='cardItem staticCard text-center']/div/h3");
	public By paintextra=By.xpath("//p[@class='extInfo']");
	public By wall_paints_int=By.linkText("Wall Paints");
	public By paint_type=By.xpath("(//a[@class='content-wp'])[1]");
	public By filter7=By.xpath("(//span[@class='for-desktop track_filter_btn'])[7]");
	public By comparepro1=By.xpath("(//span[@class='spriteIcon-Aprevamp  customCheckBox-unchecked'])[18]");
	public By comparepro2=By.xpath("(//span[@class='spriteIcon-Aprevamp  customCheckBox-unchecked'])[19]");
	public By compare=By.linkText("COMPARE");
	public By wall_textures_int=By.linkText("Wall Textures");
	public By filter8=By.xpath("(//span[@class='for-desktop track_filter_btn'])[2]");
	public By Textures_heading=By.xpath("//h3[@class='overlay-title']");
	public By Texture_discription=By.xpath("//p[@class='showOnlyMob']");
	public By kids=By.linkText("Kid's World");
	public By theme=By.xpath("//img[@class='isVisible-img--scroll']");
	public By toggle=By.xpath("//input[@class='position-absolute js-checkbox']");
	public By toggle1=By.xpath("(//input[@class='position-absolute js-checkbox'])[2]");
	public By kid_themes=By.xpath("//a[@class='image-title flex-1']");
	public By stensils=By.linkText("Stencils");
	public By wall_paints_ext=By.xpath("(//li[@class='dropdown__item--list-item'])[10]/a");
	public By filterA=By.xpath("//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[2]/div[2]/button[1]/span[3]");
	public By result_listA=By.xpath("//div[@class='blackColorText prodDesc']/h3");
	public By Textu_finishes=By.linkText("Textured Finishes");
	public By filterbutton=By.xpath("//span[contains(text(),'FILTER BY')]");
	public By tile=By.linkText("Tile Guard");
	public By tile_prop_name=By.xpath("//h5[@style='min-height: 36px;']");
	public By tile_prop_dis=By.xpath("//p[contains(text(),'Helps resist water from entering in pores of the s')]");
	public By tile_name=By.xpath("//div[@class='subtext-icon-wrapper track-main-title']");
	public By tile_dis=By.xpath("//div[@class='leftImageRightText']/a/div[2]/p");
	public By Terrrace_Tank=By.xpath("//a[contains(text(),'Terrace & Tanks')]");
	public By comparepro3=By.xpath("//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/button[1]/span[1]/span[1]");
	public By comparepro4=By.xpath("//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/button[1]/span[1]/span[1]");
	public By compareboth=By.xpath("//a[contains(text(),'Compare')]");
	public By Bathroom=By.linkText("Bathrooms");
	public By filter9=By.xpath("(//span[@class='for-desktop track_filter_btn'])[4]");
	public By Interior_wp=By.xpath("//a[contains(text(),'Interiors')]");
	public By ViewAll=By.linkText("View All");
	public By Woodpaint=By.linkText("Wood Paints");
	public By products=By.xpath("//h3[@class='overlay-title']");
	public By Metalpaint=By.linkText("Metal Paints");
	public By namevalue=By.id("enquire-name");
	public By emailvalue=By.id("enquire-email");
	public By mobilevalue=By.id("enquire-mobile");
	public By pincodevalue=By.id("enquire-pincode");
	public By enqnow=By.xpath("//button[@class='ctaText enquireForm--step-1-submit track_form_submit']");
	public By success=By.xpath("//h2[@class='thankYouTitle']");
	public By success_dis=By.xpath("//div[@class='thank-you-message']");
	public By error=By.xpath("//div[@class='form-global__field-message form-text-input__field-message']");
}
